[[items]]
title = "ASTR 100L Instructor"
date = "Fall 2025, Spring 2026"
description = "Led lab sections for ASTR 100L, an introductory astronomy course."

[[items]]
title = "ERIRA Instructor (Green Bank Observatory)"
url = "https://www.danreichart.com/erira"
date = "August 2025, June 2024, August 2025"
description = "Instructed students on 40ft/20m radio telescopes. Led undergraduate research teams in instrumentation and software projects."

[[items]]
title = "Morehead Guest Night Operator"
url = "https://skynet.unc.edu/guestnight"
date = "Fall 2022 - Present"
description = "Weekly science outreach, operating telescopes, and explaining astronomy research to the public."
